# Generated by Django 4.2.6 on 2023-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField()),
                ("username", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
